-- CREATE TABLE "games" (
-- 	"id" serial PRIMARY KEY NOT NULL,
-- 	"title" varchar(255) NOT NULL,
-- 	"genre" varchar(100) NOT NULL,
-- 	"release_year" integer NOT NULL,
-- 	"developer" varchar(100) NOT NULL,
-- 	"category" varchar(50) NOT NULL,
-- 	"is_available" boolean NOT NULL
-- );
--> statement-breakpoint
-- CREATE TABLE "users" (
-- 	"id" serial PRIMARY KEY NOT NULL,
-- 	"name" varchar(100) NOT NULL,
-- 	"password" varchar NOT NULL,
-- 	"created_at" date DEFAULT now() NOT NULL,
-- 	"updated_at" date DEFAULT now() NOT NULL
-- );
